### ISSUE TITLE
Drop `fs.promises.cp` use.

### ISSUE THREAD

**Issue by TheTrio** [SpacingBat3/ReForged#1]
Running the latest Webcord AppImage gives the following error

> /tmp/.mount_WebCorGCZ75f/usr/bin//../lib/webcord/webcord: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory

**Comment by SpacingBat3** [comment]
It seems that regenerating the build in WebCord fixed an issue (at least for `x64` builds) – however it still gives me some thoughts that I need to add a code that will verify if directory structure is correct and otherwise retry to copy files again.

**Comment by TheTrio** [comment]
Yes, the latest build works. Thanks!
