### ISSUE TITLE
Make download URL configurable

### ISSUE THREAD

**Issue by ajafff** [SpacingBat3/ReForged#4]
Currently the the download URL for the AppImage runtime is hard-coded.
For some reason my CI recently experiences sporadic ECONNRESET and ETIMEDOUT errors while downloading files from Github.

To fix this, I propose to make the download URL configurable via environment variable, similar to what Electron provides: https://www.electronjs.org/docs/latest/tutorial/installation#custom-mirrors-and-caches
This allows me to set up a cache/mirror that matches my availability requirements.

I can contribute the changes as PR if you agree with the proposed change.

**Comment by SpacingBat3** [comment]
Maybe could you add some details to your proposial – how do you think cache/mirror should be configured? Do you think of using the maker configuration or enviroment variables?

**Comment by ajafff** [comment]
I would prefer using environment variables similar to the ones Electron uses. So I would set `APPIMAGEKIT_MIRROR=https://artifactory.my-company.com/api/github/AppImageKit/` (or something similar)

The actual code change could be as easy as this

```diff
  /** A URL from which assets will be downloaded. */
- const remote = 'https://github.com/AppImage/AppImageKit/releases/download/';
+ const remote = process.env.APPIMAGEKIT_MIRROR || 'https://github.com/AppImage/AppImageKit/releases/download/';
```

Note that this proposal is not about caching downloaded files in the file system.

**Comment by SpacingBat3** [comment]
So I've implemented it based on Electron docs for `@electron/get` mirror envs – they are called and works similarly as in case of Electron ones:
https://github.com/SpacingBat3/ReForged/blob/79c75cea3e8d65688bffcb64eeaa7fd975486031/makers/appimage/src/main.ts#L78-L82
For `remote.dir` and `remote.file` you can set a placeholders from the following list:
- `{{ version }}` – resolves to AppImageKit version tag, e.g. `13`.
- `{{ filename }}` – resolves to generic name of file being part of AppImageKit distributables, e.g. `runtime` or `AppRun`.
- `{{ arch }}` – resolves to AppImage target architecture, e.g. `x86_64`.
- `{{ node.arch }}` – resolves to Node.js target architecture, e.g. `x64` (**UPDATE**).

**Comment by ajafff** [comment]
that was fast. awesome, thanks
