### ISSUE TITLE
Validation of PNG file fails in AppImage maker

### ISSUE THREAD

**Issue by k2s** [SpacingBat3/ReForged#6]
I have PNG file that fails your validation. 
The file is working with AppImage if I disable validation.
Could you use `image-type` or `file-type` to perform validation?

**Comment by SpacingBat3** [comment]
Couls you attach your PNG file to the issue? I will look for any oddities within it.

In the meantime, I will take a look if this happens to *regular* (i.e. any files that worked before) PNG files as well.

**Comment by k2s** [comment]
```term
❯ file /tmp/i.png                                                          
/tmp/i.png: PNG image data, 32 x 32, 8-bit/color RGB, non-interlaced
```

![i](https://user-images.githubusercontent.com/181014/216833220-df3ca2de-9eeb-45b5-a7d1-f3dc90e3f9ec.png)

**Comment by SpacingBat3** [comment]
@k2s FYI, the previous header seem to be the same as the one used for `XPM3`. Looks like it was put there by the mistake, but now PNG image detection should work fine.
